Mensagens_Player:
  Entrou: '&b[Gladiador] Voce entrou no gladiador, boa sorte!'
  Saiu: '&b[Gladiador] Voce saiu do gladiador, covarde!'
  Fechado: '&b[Gladiador] Nao existe nenhum evento gladiador aberto no momento'
  Ocorrendo: '&b[Gladiador] O gladiador ja esta ocorrendo no momento'
  Ja_Esta: '&b[Gladiador] Voce ja esta no gladiador'
  Nao_Esta: '&b[Gladiador] Voce nao esta no gladiador'
  Necessario_Clan: '&b[Gladiador] E necessario ter um clan para entrar no gladiador'
  Camarote: '&b[Gladiador] Voce entrou no comarote do gladiador'
  DC: '&b[Gladiador] O jogador &6<player> deu dc'
  Sair: '&b[Gladiador] O jogador &6<player> saiu do gladiador'
  Morte: '&b[Gladiador] O jogador &6<player> foi morto por &6<killer>'
  kickado: '&b[Gladiador] Voce foi kickado do gladiador por um staffer'
  Clan_Kikado: '&b[Gladiador] O seu clan foi kickado do gladiador por um staffer'
  Sem_Money: '&b[Gladiador] Voce nao tem dinheiro suficiente'
  Comando_Bloqueado: '&b[Gladiador] Esse comando esta bloqueado no gladiador'
  Default:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'  
  - '&b[Gladiador] Comandos'
  - '&b/gladiador entrar - Entra no evento gladiador'
  - '&b/gladiador sair - Sai do evento gladiador'
  - '&b/gladiador camarote - Entra no camarote do gladiador'
  - '&b/gladiador tags - Mostra quem tem as tags do evento'
  - '&b/gladiador status - Mostra o status do gladiador'
  - '&b&l&m====================================='  
  Anuncio_Cancelado:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'
  - '&b[Gladiador] Evento cancelado!'
  - '&b[Gladiador] Motivo:&6 <motivo>'
  - '&b&l&m====================================='  
  Anuncio_Aberto:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'
  - '&b[Gladiador] Evento Gladiador Aberto!'
  - '&b[Gladiador] Para participar digite &6/gladiador entrar'
  - '&b[Gladiador] Preco da entrada: &6<preco> &bCoins'
  - '&b[Gladiador] Limite de membros por clan: &6<limite>'
  - '&b[Gladiador] Numero de players: &6<players>'
  - '&b[Gladiador] Numero de clans: &6<clans>'
  - '&b&l&m====================================='
  Anuncio_Iniciado:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'
  - '&b[Gladiador] Gladiador Em Andamento!'
  - '&b[Gladiador] Clans &6<clans>'
  - '&b[Gladiador] Players &6<players>'
  - '&b&l&m====================================='
  Anuncio_Fim:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'
  - '&b[Gladiador] Fim Do Gladiador!'
  - '&b[Gladiador] O clan vencedor foi: &6<vencedor>'
  - '&b[Gladiador] Tags Gladiador dadas para: &6<gladiadores>'
  - '&b[Gladiador] Tag Mito dada para: &6<mito>'
  - '&b&l&m====================================='
  Tags:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'
  - '&b[Gladiador] Tags'
  - '&bGladiadores: &6<gladiadores>'
  - '&bMito: &6<mito>'
  - '&bClan vencedor: &6<vencedor>'
  - '&b&l&m====================================='
  Status:
  - '&b&l&m============-&b&l[GLADIADOR]&b&l&m-============'
  - '&b[Gladiador] Status'
  - '&bJogadores Vivos: &6<jogadores>'
  - '&bClans Paricipantes: &6<clans>'
  - '&b&l&m====================================='
Localizacoes:
  Spawn_Entrada:
    World: Gladiador
    X: -662.4295186663979
    Y: 4.0
    Z: 1468.097419182741
  Spawn_Saida:
    World: spawn
    X: -53.51990697373702
    Y: 72.0
    Z: 40.51160677907059
  Spawn_Camarote:
    World: Gladiador
    X: -665.5430891305441
    Y: 48.0
    Z: 1487.8341956365075
Gladiador:
  Deixar_De_Noite: true
  Retirar_Chuva: true
  Anuncio_Quantidade: 2
  Anuncio_Tempo_Entre_As_Mensagens: 10
  Limite_De_Membros: 30
  Eliminar_Randomicamente_Limite: true
  Preco_Para_Entrar: 1000
  Necessario_Ter_Clan_Para_Participar: true
  Ativar_Mensagens_De_Morte: true
  Ativar_Mensagens_De_Sair: true
  Ativar_Mensagens_De_DC: true
  Ultimo_Clan_Vencedor: ABC
Gladiador_Premio:
  Money_Para_Cada_Integrante: 10000
  Money_Para_Cada_Lider: 100000
Mito_Tag:
  Tag: '&5[Mito]'
  Jogador_Com_A_Tag_Atual: SkelletonX
Gladiador_Tag:
  Quantidade: 1
  Tag: '&c[Gladiador]'
  Jogador_Com_A_Tag_Atual: SkelletonX
Automacao:
  Ativar: true
  Dia: 6
  Hora: 22
  Minuto: 30
Clan_Tag:
  Ativar_Tab_Tag: true
  Formato_Com_Clan: '{clantag}&8.&f'
  Formato_Sem_Clan: '&f'
  Tempo_Para_Atualizar: 30
Comandos_Bloqueados:
- /spawn
- /home
- /warp